using _1stApp;

var employee1 = new Employee("Stefan", "Kowalski");
employee1.AddGrade("Adam");
employee1.AddGrade("101");
employee1.AddGrade(10);
employee1.AddGrade(100);
employee1.AddGrade(0.004);
var statistics = employee1.GetStatistics();
var statistics1 = employee1.GetStatisticsWithForEach();
var statistics2 = employee1.GetStatisticsWithFor();
var statistics3 = employee1.GetStatisticsWithDoWhile();
var statistics4 = employee1.GetStatisticsWithWhile();
Console.WriteLine($"{"Loop Foreach",15} | {"Loop For",15} | {"Loop DoWhile",15} | {"Loop While",15}");
Console.WriteLine($"Grades No:");
Console.WriteLine($"{statistics1.Counter,15} | {statistics2.Counter,15} | {statistics3.Counter,15} | {statistics4.Counter,15}");
Console.WriteLine($"Min:");
Console.WriteLine($"{statistics1.Min,15} | {statistics2.Min,14}  |  {statistics3.Min,14} | {statistics4.Min,14}");
Console.WriteLine($"Max");
Console.WriteLine($"{statistics1.Max,15} | {statistics2.Max,14}  |  {statistics3.Max,14} | {statistics4.Max,14}");
Console.WriteLine($"Average");
Console.WriteLine($"{statistics1.Average,15} | {statistics2.Average,14}  |  {statistics3.Average,14} | {statistics4.Average,15}");
